//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double unit_price { get; set; }
        public int quantity { get; set; }
        public string photo1 { get; set; }
        public string photo2 { get; set; }
        public string photo3 { get; set; }
        public string catagory { get; set; }
    }
}
